/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingImport } from './routes/setting'
import { Route as HowToUseImport } from './routes/how-to-use'
import { Route as CommandsImport } from './routes/commands'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SettingRoute = SettingImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRoute,
} as any)

const HowToUseRoute = HowToUseImport.update({
  id: '/how-to-use',
  path: '/how-to-use',
  getParentRoute: () => rootRoute,
} as any)

const CommandsRoute = CommandsImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsImport
      parentRoute: typeof rootRoute
    }
    '/how-to-use': {
      id: '/how-to-use'
      path: '/how-to-use'
      fullPath: '/how-to-use'
      preLoaderRoute: typeof HowToUseImport
      parentRoute: typeof rootRoute
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/how-to-use': typeof HowToUseRoute
  '/setting': typeof SettingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/how-to-use': typeof HowToUseRoute
  '/setting': typeof SettingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/how-to-use': typeof HowToUseRoute
  '/setting': typeof SettingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/commands' | '/how-to-use' | '/setting'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/commands' | '/how-to-use' | '/setting'
  id: '__root__' | '/' | '/commands' | '/how-to-use' | '/setting'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandsRoute: typeof CommandsRoute
  HowToUseRoute: typeof HowToUseRoute
  SettingRoute: typeof SettingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandsRoute: CommandsRoute,
  HowToUseRoute: HowToUseRoute,
  SettingRoute: SettingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/commands",
        "/how-to-use",
        "/setting"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/commands": {
      "filePath": "commands.tsx"
    },
    "/how-to-use": {
      "filePath": "how-to-use.tsx"
    },
    "/setting": {
      "filePath": "setting.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
